-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. PRODUCTS TABLE
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL,
    stock_quantity INTEGER DEFAULT 0,
    motor_slot_id INTEGER NOT NULL UNIQUE, -- Mechanical slot ID (e.g., 1, 2, 3...)
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. ORDERS TABLE
CREATE TABLE public.orders (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id), -- Links to Supabase Auth User
    product_id BIGINT REFERENCES public.products(id),
    status TEXT CHECK (status IN ('PENDING', 'PAID', 'DISPENSED', 'CANCELLED')) DEFAULT 'PENDING',
    amount NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. QR TOKENS TABLE
CREATE TABLE public.qr_tokens (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    order_id UUID REFERENCES public.orders(id),
    token_hash TEXT NOT NULL UNIQUE, -- Secure hash of the payload
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS POLICIES (Row Level Security)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qr_tokens ENABLE ROW LEVEL SECURITY;

-- Products are readable by everyone, writable only by admins (service_role)
CREATE POLICY "Public products are viewable by everyone" ON public.products
    FOR SELECT USING (true);

-- Orders are viewable by the user who created them
CREATE POLICY "Users can view own orders" ON public.orders
    FOR SELECT USING (auth.uid() = user_id);

-- Only authenticated users can insert orders
CREATE POLICY "Users can create orders" ON public.orders
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Mock Data for Testing
INSERT INTO public.products (name, description, price, stock_quantity, motor_slot_id, image_url)
VALUES
('Cola', 'Chilled sparkling soda', 1.50, 10, 1, 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97'),
('Chips', 'Salted potato chips', 2.00, 15, 2, 'https://images.unsplash.com/photo-1566478919030-26d9eecbed10'),
('Chocolate', 'Dark chocolate bar', 2.50, 20, 3, 'https://images.unsplash.com/photo-1511381978801-6fbb6316cd04');
